services:

  db:
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  web:
    build:
      target: app
      args:
        APP_ENV: prod
    environment:
      APP_ENV: prod
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
