services:

  db:
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  web:
    build:
      target: production_ready
      args:
        APP_ENV: prod
    environment:
      APP_ENV: prod
    restart: unless-stopped

  redis:
    restart: unless-stopped

volumes:
  mysql_data:
