services:

  db:
    image: mariadb:10.9.5
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - ./docker/db/db-backup.sh:/usr/local/bin/db-backup.sh

  web:
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: dev_build
    environment:
      APP_SECRET: ${APP_SECRET:-secret}
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-app}@db/${MYSQL_DATABASE:-app}
      SITE_URI: http://127.0.0.1:${WEB_HTTP_PORT:-8000}/
      MAILER_DSN: null://null
      SUPER_ADMIN_EMAIL: admin@example.com
      SSL_SUBJECT:
      MAILER_SENDER_ADDRESS: changeme@example.com
      MAILER_SENDER_NAME: ChangeMe
    ports:
      - "${WEB_HTTP_PORT:-8000}:80"
      - "${WEB_HTTPS_PORT:-8443}:443"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
